#!/bin/bash
# db-init/01-create-users.sh
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL

    CREATE USER "$APP_USER" WITH PASSWORD '$APP_USER_PASSWORD';

    GRANT CONNECT ON DATABASE "$POSTGRES_DB" TO "$APP_USER";

    GRANT USAGE, CREATE ON SCHEMA public TO "$APP_USER";

    GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO "$APP_USER";

    ALTER DEFAULT PRIVILEGES IN SCHEMA public
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO "$APP_USER";
EOSQL

#RUN WHEN CONTAINER RESTARTS / NEW MIGRATION IS READY
#docker compose exec backend npx drizzle-kit migrate